[package]
name = "ccrs-search"
version = "0.1.0"
edition = "2024"

[dependencies]
ccrs-utils = { path = "../utils" }
tantivy = "0.25"
ignore = "0.4"
anyhow = "1"
fastembed = "4"
dirs = "6"

[dev-dependencies]
tempfile = "3"
